source "https://api.berkshelf.com"

cookbook "apt"
cookbook "ntp"
cookbook "openssh"
cookbook "htop"
cookbook "git"
cookbook "build-essential"
cookbook "java"
cookbook "scala"
cookbook "maven"
cookbook "erlang"
